
Vagrant.configure("2") do |config|
 
  config.vm.box = "debian/bullseye64"

  config.vm.define "venus" do |venus|
    venus.vm.hostname = "venus.sistema.test"
    venus.vm.network "private_network", ip: "192.168.57.102"
    venus.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    venus.vm.provision "shell", inline: <<-SHELL
      apt-get update       
      apt-get -y install bind9 bind9-dnsutils
    SHELL
  end

  config.vm.define "tierra" do |tierra|
    tierra.vm.hostname = "tierra.sistema.test"
    tierra.vm.network "private_network", ip: "192.168.57.103"
    tierra.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    tierra.vm.provision "shell", inline: <<-SHELL
      apt-get update 
      apt-get -y install bind9 bind9-dnsutils
    SHELL
  end
end
