Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.hostname = "nginx"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update

    apt-get install -y nginx 
    apt-get install -y vsftpd 

    mkdir  /var/www/web_ngnix/
    mkdir  /var/www/web_ngnix/html

    cp /vagrant/files/example.html /var/www/web_nginx/html
    cp /vagrant/files/web_nginx /etc/nginx/sites-available/

    rm /etc/nginx/sites-available/default

    ln -s /etc/nginx/sites-available/web_nginx /etc/nginx/sites-enabled/

    chown -R www-data:www-data /var/www/web_gnix/html
    chmod -R 755 /var/www/web_gnix/

    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/vsftpd.key -out /etc/ssl/certs/vsftpd.crt

    cp /vagrant/files/vsftpd.conf /etc/vsftpd.conf

    # Fin practica 2.1

    install openssl

    sh -c "echo -n 'Alejandro:' >> /etc/nginx/.htpasswd" 
    sh -c "openssl passwd -apr1 '1234'>> /etc/nginx/.htpasswd" 

    sh -c "echo -n 'Aguilera:' >> /etc/nginx/.htpasswd" 
    sh -c "openssl passwd -apr1 '4321'>> /etc/nginx/.htpasswd" 

    # Creacion de la nueva web

    mkdir  /var/www/perfer/

    cp -r /vagrant/files/html /var/www/perfer/
    cp /vagrant/files/perfer /etc/nginx/sites-available/

    ln -s /etc/nginx/sites-available/perfer /etc/nginx/sites-enabled/

    # FIn practica 2.2

    apt-get install ufw

    ufw allow ssh
    ufw allow 'Nginx Full'
    ufw delete allow 'Nginx HTTP'

    ufw --force enable

    systemctl restart nginx
    systemctl restart vsftpd
  SHELL
end
